### PR TITLE
Rewrited network, firewall and keepalived

### PR DESCRIPTION
**Pull request by feldsam**
Added support for loadballancing, NAT, alpine 3.5 etc...

I rewrited to use PHP because I am more confortable with that insted of bash scripts. I hope that it is not a big problem, I can easily and quicker extend that code and I am open to help maintain this repo.

### CODE REVIEW

**Comment by FlorianHeigl** [comment]
Could you please keep the vrouter PHP part separate of the normal context? 
For the vrouter I suppose it's fine, but the base context for **all** OS is just using native shell.

**Comment by feldsam** [comment]
Hello, by "base" you means just network and dns? I can revert that two and enable ipv6 in it.

**Comment by jfontan** [comment]
I believe that it's better to keep your developments in another repository. I can create a repo in this organization for you if needed.

Most probably we will have to split somehow the base Alpine context scripts (configure network, start script, ssh, etc) and virtual router related scripts.

**Comment by FlorianHeigl** [comment]
Hi @feldsam sorry for the delay... what I meant is right now **all** context scripts for **all** distributions work roughly the same way, and use shell.
I used "base" trying to say "anything that is in /etc/one.context.d, /etc/udev or /usr/*bin and is done as context for the other linux distros / bsd's...)

The vrouter specific parts aren't "base" I think they could be in any language.

Easiest way would be if you do the exact same thing as you did, but don't use a different language.
I'd like to move this forward with you, but it would be good if the (non-vrouter) context scripts are not requiring a different language :)

The main factor for this is that it's a very hard task try to have feature parity between the context scripts for different distos. we made some progress towards that - and we should try to not make it harder again.

**Comment by FlorianHeigl** [comment]
and i just found https://github.com/jirutka/one-context so now we already again managed to have multiple versions of the same thing (as it was for sles, as for freebsd)
using non-standard parts too and upstream in alpine... 
I'll just go get some drinks ;-)

**Comment by vholer** [comment]
I have seen https://github.com/jirutka/one-context some time ago and was surprised as well. Having conflicting project/package names is unfortunate.

Anyway, we have managed to merge the Alpine scripts into general Linux contextualization repo, and we can benefit from shared code parts across the platforms there.

I don't dare to close this PR but honestly must say I don't believe there is much chance of merging something rewritten into the PHP. We don't need the POSIX shell purity (as Jakub's simple one-context has), but depending on the PHP beast is overkill. With all respect to the proposed changes.

This repo is now considered as obsolete:
https://opennebula.org/new-linux-contextualization-packages/

**Comment by feldsam** [comment]
Hi all, I understand PHP problem :) so I keep it for internal use, because I am not so comfortable with bash as with php. It was easier for me to wrote it in PHP. I am closing this PR. Thank you for comments.

**Pull request closed without merging**
